[
  {
    "id": 108,
    "project_id": 53,
    "task_name": "需求评审",
    "task_type": "group",
    "degreen": 0,
    "priority": 0,
    "task_time": "0.00",
    "start_time": null,
    "end_time": null,
    "developer_id": "",
    "developer_name": "",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 109,
    "project_id": 53,
    "task_name": "需求评审(开发A)",
    "task_type": "normal",
    "degreen": 3,
    "priority": 0,
    "task_time": "1.00",
    "start_time": "2020-10-01T01:00:00.000Z",
    "end_time": "2020-10-01T10:00:00.000Z",
    "developer_id": "2",
    "developer_name": "陈今斌",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 110,
    "project_id": 53,
    "task_name": "高保真评审",
    "task_type": "group",
    "degreen": 0,
    "priority": 0,
    "task_time": "0.00",
    "start_time": null,
    "end_time": null,
    "developer_id": "",
    "developer_name": "",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 111,
    "project_id": 53,
    "task_name": "高保真评审(开发A)",
    "task_type": "normal",
    "degreen": 3,
    "priority": 0,
    "task_time": "1.00",
    "start_time": "2020-10-02T01:00:00.000Z",
    "end_time": "2020-10-02T10:00:00.000Z",
    "developer_id": "2",
    "developer_name": "陈今斌",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 112,
    "project_id": 53,
    "task_name": "任务分组名称",
    "task_type": "group",
    "degreen": 0,
    "priority": 0,
    "task_time": "0.00",
    "start_time": null,
    "end_time": null,
    "developer_id": "",
    "developer_name": "",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 113,
    "project_id": 53,
    "task_name": "任务1",
    "task_type": "normal",
    "degreen": 3,
    "priority": 0,
    "task_time": "1.00",
    "start_time": "2020-10-05T01:00:00.000Z",
    "end_time": "2020-10-05T10:00:00.000Z",
    "developer_id": "2",
    "developer_name": "陈今斌",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 114,
    "project_id": 53,
    "task_name": "一级用例自验",
    "task_type": "group",
    "degreen": 0,
    "priority": 0,
    "task_time": "0.00",
    "start_time": null,
    "end_time": null,
    "developer_id": "",
    "developer_name": "",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 115,
    "project_id": 53,
    "task_name": "一级用例自验(开发A)",
    "task_type": "normal",
    "degreen": 3,
    "priority": 0,
    "task_time": "1.00",
    "start_time": "2020-10-06T01:00:00.000Z",
    "end_time": "2020-10-06T10:00:00.000Z",
    "developer_id": "2",
    "developer_name": "陈今斌",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 116,
    "project_id": 53,
    "task_name": "UI验收意见修改",
    "task_type": "group",
    "degreen": 0,
    "priority": 0,
    "task_time": "0.00",
    "start_time": null,
    "end_time": null,
    "developer_id": "",
    "developer_name": "",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 117,
    "project_id": 53,
    "task_name": "UI验收意见修改(开发A)",
    "task_type": "normal",
    "degreen": 3,
    "priority": 0,
    "task_time": "1.00",
    "start_time": "2020-10-07T01:00:00.000Z",
    "end_time": "2020-10-07T10:00:00.000Z",
    "developer_id": "2",
    "developer_name": "陈今斌",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 118,
    "project_id": 53,
    "task_name": "转测改单",
    "task_type": "group",
    "degreen": 0,
    "priority": 0,
    "task_time": "0.00",
    "start_time": null,
    "end_time": null,
    "developer_id": "",
    "developer_name": "",
    "progress": 0,
    "remark": ""
  },
  {
    "id": 119,
    "project_id": 53,
    "task_name": "转测改单(开发A)",
    "task_type": "normal",
    "degreen": 3,
    "priority": 0,
    "task_time": "1.00",
    "start_time": "2020-10-08T01:00:00.000Z",
    "end_time": "2020-10-08T10:00:00.000Z",
    "developer_id": "2",
    "developer_name": "陈今斌",
    "progress": 0,
    "remark": ""
  }
]